### ISSUE TITLE
Adicionar nome no readme

### ISSUE THREAD

**Issue by NicolasSilvaDA** [NicolasSilvaDA/GCMS-Nicolas-Araujo#2]
[README](https://github.com/NicolasSilvaDA/GCMS-Nicolas-Araujo/edit/main/README.md) @ramidedantas

**Comment by ramidedantas** [comment]
@NicolasSilvaDA coloque o Readme no formato que botei no meu repo, com lista de colaboradores.

**Comment by NicolasSilvaDA** [comment]
@ramidedantas Pronto, professor, agora o senhor pode colocar o seu nome

**Comment by ramidedantas** [comment]
@NicolasSilvaDA Ok, pode fechar a issue.
